# Generated by Django 4.2.2 on 2024-07-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_ethereum_wallet_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ethereum_wallet_address",
        ),
        migrations.AddField(
            model_name="profile",
            name="ethereum_balance",
            field=models.DecimalField(
                blank=True, decimal_places=18, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="ethereum_wallet_address",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
